version: 1.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

platform: Any CPU

configuration: Release

build_script:
  - ps: dotnet --info
  #- ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet test .\RandomUserTest
  - ps: dotnet pack -o .\artifacts\

artifacts:
  - path: randomuser\artifacts\*.nupkg
    name: NuGet

branches:
  only:
    - master

deploy:
  provider: NuGet
  api_key:
    secure: FOub18t4gH9fknL/YZcPTZM+UtBs9cZYLajeiQLdvGS1iheRmBkELQ1SYWDqKxoD
  skip_symbols: false
  artifact: /.*\.nupkg/
