version: 1.0.{build}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

platform: Any CPU

configuration: Release

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet test .\RandomUserTtest
  - ps: dotnet pack -o .\artifacts\

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: randomuser\artifacts\*.nupkg
    name: NuGet

branches:
  only:
    - master

deploy:
  provider: NuGet
  api_key:
    secure: 65DMGVnniyCfcu6cf50N//7QAj2SHmWkkx4zpeatI42x7UHeTApWDJDEUQPcFlzf
  skip_symbols: false
  artifact: /.*\.nupkg/
